const skill = [
    {
      "id": '1',
      "imgs": "/images/p1.png",
      "webName": "ChitChat Chating App",
      "name": "chitchat",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",
      "react": "REACT",
      "tailwind": "TAILWIND",
      "title": ["TAILWIND", "REACT JS", "DAYNAMIC"]
    },
    {
      "id": '2',
      "imgs": "/images/p2.png",
      "webName": "Orebi E-Commerce",      
      "name": "Orebi",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",
      "react": "REACT",
      "tailwind": "TAILWIND",
      "redux": "REDUX",
      "title": ["TAILWIND", "REACT JS", "DAYNAMIC"]
    },
    {
      "id": '3',
      "imgs": "/images/p3.png",
      "webName": "My Portfolio",
      "name": "Portfolio",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",
      "react": "REACT",
      "tailwind": "TAILWIND",
      "redux": "REDUX",
      "title": [ "TAILWIND","DAYNAMIC","REACT JS"]
    },
    {
      "id": '4',
      "imgs": "/images/p4.png",
      "webName": "OMAH",
      "name": "Omah",
      "paragraph": "This is a Aaricle Website. The website is fully responsive. Created the website to practice Sass. I have used HTML, CSS and Sass to create this website.",
      "html": "HTML5",
      "css": "CSS3",     
      "title": ["BOOTSTRAP"]
    }, 
    {
      "id": '5',
      "imgs": "/images/p5.png",
      "webName": "QuiriBox",
      "name": "QuiriBox",
      "paragraph": "This is a Aaricle Website. The website is fully responsive. Created the website to practice Sass. I have used HTML, CSS and Sass to create this website.",
      "html": "HTML5",
      "css": "CSS3",     
      "title": ["BOOTSTRAP"]
    },
    {
      "id": '6',
      "imgs": "/images/p6.png",
      "webName": "PETROIL",
      "name": "petroil",
      "paragraph": "This is a Aaricle Website. The website is fully responsive. Created the website to practice Sass. I have used HTML, CSS and Sass to create this website.",
      "html": "HTML5",
      "css": "CSS3",     
      "title": ["BOOTSTRAP"]
    },
    {
      "id": '7',
      "imgs": "/images/p7.png",
      "webName": "MixiTup",
      "name": "MixiTup",
      "paragraph": "This is a Aaricle Website. The website is fully responsive. Created the website to practice Sass. I have used HTML, CSS and Sass to create this website.",
      "tailwind": "TAILWIND",   
      "react": "REACT", 
      "title": [ "REACT JS","TAILWIND" ]
    }, 
      {
      "id": '8',
      "imgs": "/images/p8.png",
      "webName": "Instagram Clone",
      "name": "Insta",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",
      "react": "REACT",
      "tailwind": "TAILWIND",
      "title": [ "DAYNAMIC","TAILWIND", "REACT JS"]
    },
      {
      "id": '9',
      "imgs": "/images/p9.png",
      "webName": "Javascript Todo",
      "name": "Todo",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["JAVASCRIPT"]
    },{
      "id": '10',
      "imgs": "/images/p10.png",
      "webName": "Javascript Todo Complex",
      "name": "complex",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["JAVASCRIPT"]
    }, {
      "id": '11',
      "imgs": "/images/p11.png",
      "webName": "Javascript Slider",
      "name": "slider",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["JAVASCRIPT"]
    },
     {
      "id": '12',
      "imgs": "/images/p12.png",
      "webName": "Redux Signup Login Dashboard",
      "name": "redux",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "react": "REACT",
      "tailwind": "TAILWIND",
      "redux": "REDUX",    
      "title": [ "REACT JS","TAILWIND"]
    },
    {
      "id": '13',
      "imgs": "/images/p13.png",
      "webName": "Love Website",
      "name": "love",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["BOOTSTRAP"]
    },
      {
      "id": '14',
      "imgs": "/images/p14.png",
      "webName": "FinsWet",
      "name": "finswet",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["BOOTSTRAP"]
    }, 
      {
      "id": '15',
      "imgs": "/images/p15.png",
      "webName": "Query",
      "name": "query",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["BOOTSTRAP"]
    },
     {
      "id": '16',
      "imgs": "/images/p16.png",
      "webName": "Innovate",
      "name": "innovate",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["BOOTSTRAP"]
    },
     {
      "id": '17',
      "imgs": "/images/p17.png",
      "webName": "Demo Portfolio",
      "name": "demo",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS", 
       "react": "REACT",
      "tailwind": "TAILWIND",
      "redux": "REDUX",   
      "title": ["DAYNAMIC","TAILWIND", "REACT JS" ]
    },
     {
      "id": '18',
      "imgs": "/images/p18.png",
      "webName": "Toggle React",
      "name": "toggle",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS", 
       "react": "REACT",
      "tailwind": "TAILWIND",    
      "title": ["REACT JS","TAILWIND"]
    }, {
      "id": '19',
      "imgs": "/images/p19.png",
      "webName": "Guessing Game Javascript",
      "name": "guessing",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["JAVASCRIPT"]
    },
    {
      "id": '20',
      "imgs": "/images/p20.png",
      "webName": "Toggle React",
      "name": "react",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS", 
       "react": "REACT",
      "tailwind": "TAILWIND",    
      "title": ["TAILWIND", "REACT JS"]
    }, {
      "id": '21',
      "imgs": "/images/p21.png",
      "webName": "Pet Store And Beyond",
      "name": "pet",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",
      "js": "JS",    
      "title": ["BOOTSTRAP"]
    }, 
    {
      "id": '22',
      "imgs": "/images/p22.png",
      "webName": "Colour Meaching",
      "name": "colour",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",   
      "title": ["BOOTSTRAP"]
    }, 
    {
      "id": '23',
      "imgs": "/images/p23.png",
      "webName": "E-School",
      "name": "school",
      "paragraph": "On this website, user and vendors can sign up and log in. The seller can sell the product and the user can buy the product. The website is fully responsive.",
      "html": "HTML5",
      "css": "CSS3",   
      "title": ["BOOTSTRAP"]
    },
  ];
  
  export default skill;
  